/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_a_Y (XDR *xdrs, a_Y *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_min (XDR *xdrs, max_min objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_a_mul_Y (XDR *xdrs, a_mul_Y *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->a_mul_Y_val, (u_int *) &objp->a_mul_Y_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
