/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

float *
avg_1(a_Y *argp, CLIENT *clnt)
{
	static float clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AVG,
		(xdrproc_t) xdr_a_Y, (caddr_t) argp,
		(xdrproc_t) xdr_float, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
max_min_1(a_Y *argp, CLIENT *clnt)
{
	static max_min clnt_res;

	memset((char *)clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MAX_MIN,
		(xdrproc_t) xdr_a_Y, (caddr_t) argp,
		(xdrproc_t) xdr_max_min, (caddr_t) clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (clnt_res);
}

a_mul_Y *
mul_a_y_1(a_Y *argp, CLIENT *clnt)
{
	static a_mul_Y clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MUL_a_Y,
		(xdrproc_t) xdr_a_Y, (caddr_t) argp,
		(xdrproc_t) xdr_a_mul_Y, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
