/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

void
calc_prog_1(char *host)
{
	CLIENT *clnt;

	float  *result_1;	// Float number
	a_Y  avg_1_arg;	// struct a_Y

	int  *result_2;	// Array of 2 integer numbers
	a_Y  max_min_1_arg; // struct a_Y

	a_mul_Y  *result_3;	// Vector of n float numbers
	a_Y  mul_a_y_1_arg; // struct a_Y

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	avg_1_arg.a = 0.5;
	avg_1_arg.Y.Y_len = 3;
	avg_1_arg.Y.Y_val = (int *)malloc(3 * sizeof(int));
	avg_1_arg.Y.Y_val[0] = 6;
	avg_1_arg.Y.Y_val[0] = 5;
	avg_1_arg.Y.Y_val[0] = 6;



	result_1 = avg_1(&avg_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("AVG function was called");
	}

	free(avg_1_arg.Y.Y_val);


	result_2 = max_min_1(&max_min_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mul_a_y_1(&mul_a_y_1_arg, clnt);
	if (result_3 == (a_mul_Y *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG 
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host);
exit (0);
}
