/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <stdlib.h>

float *
avg_1_svc(a_Y *argp, struct svc_req *rqstp)
{
	static float  result;
	float sum = 0.0;

	printf("Average function was called...\n");
	if (argp->Y.Y_len == 0) {
		printf("Error: Vector Y is empty...\n");
		return NULL;
	}

	for (int i = 0; i < argp->Y.Y_len; i++) {
		sum += argp->Y.Y_val[i];
	}
	result = sum / argp->Y.Y_len;

	return &result;
}

int *
max_min_1_svc(a_Y *argp, struct svc_req *rqstp)
{
	printf("Max/Min function was called...\n");

	// Check if array Y from client is empty
	if (argp->Y.Y_len == 0) {
		printf("Error: Vector Y is empty...\n");
		return NULL;
	}

	static int  result[2];
	int max = argp->Y.Y_val[0];
	int min = argp->Y.Y_val[0];
	
	for (int i = 1; i < argp->Y.Y_len; i++) {
		if (max < argp->Y.Y_val[i]) {
			max = argp->Y.Y_val[i];
		}

		if (min > argp->Y.Y_val[i]) {
			min = argp->Y.Y_val[i];
		}
	}

	result[0] = max;
	result[1] = min;

	return result;
}

a_mul_Y *
mul_a_y_1_svc(a_Y *argp, struct svc_req *rqstp)
{
	printf("Mul function was called...\n");

	static a_mul_Y  result;
	if (result.a_mul_Y_val != NULL) {
		free(result.a_mul_Y_val);
	}

	result.a_mul_Y_len = argp->Y.Y_len;
	result.a_mul_Y_val = (float *)malloc(result.a_mul_Y_len * sizeof(float));
	if (!result.a_mul_Y_val) {
		printf("Memory allocation error...\n");
		return NULL;
	}

	for (int i = 0; i < argp->Y.Y_len; i++) {
		result.a_mul_Y_val[i] = argp->a * argp->Y.Y_val[i];
	}

	return &result;
}
