/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct a_Y {
	float a;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct a_Y a_Y;

typedef int max_min[2];

typedef struct {
	u_int a_mul_Y_len;
	float *a_mul_Y_val;
} a_mul_Y;

#define CALC_PROG 0x23451111
#define CALC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define AVG 1
extern  float * avg_1(a_Y *, CLIENT *);
extern  float * avg_1_svc(a_Y *, struct svc_req *);
#define MAX_MIN 2
extern  int * max_min_1(a_Y *, CLIENT *);
extern  int * max_min_1_svc(a_Y *, struct svc_req *);
#define MUL_a_Y 3
extern  a_mul_Y * mul_a_y_1(a_Y *, CLIENT *);
extern  a_mul_Y * mul_a_y_1_svc(a_Y *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AVG 1
extern  float * avg_1();
extern  float * avg_1_svc();
#define MAX_MIN 2
extern  int * max_min_1();
extern  int * max_min_1_svc();
#define MUL_a_Y 3
extern  a_mul_Y * mul_a_y_1();
extern  a_mul_Y * mul_a_y_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_a_Y (XDR *, a_Y*);
extern  bool_t xdr_max_min (XDR *, max_min);
extern  bool_t xdr_a_mul_Y (XDR *, a_mul_Y*);

#else /* K&R C */
extern bool_t xdr_a_Y ();
extern bool_t xdr_max_min ();
extern bool_t xdr_a_mul_Y ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
