/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
avg_1_svc(a_Y *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
max_min_1_svc(a_Y *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

a_mul_Y *
mul_a_y_1_svc(a_Y *argp, struct svc_req *rqstp)
{
	static a_mul_Y  result;

	/*
	 * insert server code here
	 */

	return &result;
}
